import type { Product } from "./types"

export const products: Product[] = [
  // Clothes
  {
    id: "1",
    name: "Premium Cotton T-Shirt",
    description:
      "Soft, breathable cotton t-shirt perfect for everyday wear. Features a relaxed fit and durable stitching.",
    price: 3500,
    originalPrice: 4500,
    image: "/white-cotton-t-shirt-on-hanger.jpg",
    category: "clothes",
    rating: 4.5,
    reviews: 128,
    inStock: true,
    tags: ["bestseller", "sustainable"],
    stock: 20,
  },
  {
    id: "2",
    name: "Slim Fit Denim Jeans",
    description:
      "Classic slim fit jeans crafted from premium stretch denim. Comfortable all-day wear with timeless style.",
    price: 9500,
    image: "/blue-denim-jeans-folded.jpg",
    category: "clothes",
    rating: 4.7,
    reviews: 256,
    inStock: true,
    tags: ["popular"],
    stock: 20,
  },
  {
    id: "3",
    name: "Wool Blend Overcoat",
    description: "Elegant wool blend overcoat with a tailored silhouette. Perfect for layering in cooler weather.",
    price: 24000,
    originalPrice: 29000,
    image: "/beige-wool-overcoat-elegant.jpg",
    category: "clothes",
    rating: 4.8,
    reviews: 89,
    inStock: true,
    tags: ["premium"],
    stock: 20,
  },
  {
    id: "4",
    name: "Linen Summer Dress",
    description: "Light and airy linen dress ideal for warm weather. Features a flattering A-line silhouette.",
    price: 10500,
    image: "/white-linen-summer-dress.jpg",
    category: "clothes",
    rating: 4.6,
    reviews: 167,
    inStock: true,
    stock: 20,
  },
  // Shoes
  {
    id: "5",
    name: "Leather Sneakers",
    description: "Minimalist leather sneakers with cushioned insoles. Perfect blend of comfort and style.",
    price: 15500,
    image: "/white-leather-sneakers-minimal.jpg",
    category: "shoes",
    rating: 4.9,
    reviews: 312,
    inStock: true,
    tags: ["bestseller"],
    stock: 20,
  },
  {
    id: "6",
    name: "Classic Oxford Shoes",
    description:
      "Handcrafted leather oxford shoes with traditional brogue detailing. Timeless elegance for formal occasions.",
    price: 22500,
    originalPrice: 27500,
    image: "/brown-leather-oxford-shoes.jpg",
    category: "shoes",
    rating: 4.7,
    reviews: 98,
    inStock: true,
    tags: ["premium"],
    stock: 20,
  },
  {
    id: "7",
    name: "Running Performance Shoes",
    description: "Lightweight running shoes with responsive cushioning and breathable mesh upper.",
    price: 18000,
    image: "/black-running-shoes-athletic.jpg",
    category: "shoes",
    rating: 4.8,
    reviews: 445,
    inStock: true,
    tags: ["popular"],
    stock: 20,
  },
  {
    id: "8",
    name: "Suede Chelsea Boots",
    description: "Classic Chelsea boots in premium suede. Elastic side panels for easy on-off wear.",
    price: 20000,
    image: "/tan-suede-chelsea-boots.jpg",
    category: "shoes",
    rating: 4.6,
    reviews: 134,
    inStock: true,
    stock: 20,
  },
  // Cosmetics
  {
    id: "9",
    name: "Luminous Foundation",
    description: "Buildable coverage foundation with a natural luminous finish. Enriched with skincare ingredients.",
    price: 5000,
    image: "/luxury-foundation-bottle-makeup.jpg",
    category: "cosmetics",
    rating: 4.7,
    reviews: 523,
    inStock: true,
    tags: ["bestseller"],
    stock: 20,
  },
  {
    id: "10",
    name: "Velvet Matte Lipstick Set",
    description: "Collection of 6 velvet matte lipsticks in versatile shades. Long-wearing and comfortable formula.",
    price: 6500,
    originalPrice: 8500,
    image: "/lipstick-set-various-colors.jpg",
    category: "cosmetics",
    rating: 4.8,
    reviews: 289,
    inStock: true,
    tags: ["popular"],
    stock: 20,
  },
  {
    id: "11",
    name: "Hydrating Eye Cream",
    description:
      "Intensive eye cream that reduces puffiness and dark circles. Powered by peptides and hyaluronic acid.",
    price: 7000,
    image: "/luxury-eye-cream-jar-skincare.jpg",
    category: "cosmetics",
    rating: 4.5,
    reviews: 178,
    inStock: true,
    tags: ["skincare"],
    stock: 20,
  },
  {
    id: "12",
    name: "Multi-Palette Eyeshadow",
    description: "18 highly pigmented shades from matte to shimmer. Perfect for day to night looks.",
    price: 6000,
    image: "/eyeshadow-palette-neutral-colors.jpg",
    category: "cosmetics",
    rating: 4.9,
    reviews: 612,
    inStock: true,
    tags: ["bestseller"],
    stock: 20,
  },
  // Perfumes
  {
    id: "13",
    sku: "LIO-PRF-001",
    name: "The Kingdom Eau de Parfum",
    description: "A regal and refined masculine scent with refreshing notes of Lavender, Mint, and Sage, grounded by a warm heart of Vanilla and Tobacco.",
    price: 4000,
    image: "/king1.jpg",
    images: ["/king1.jpg", "/king2.jpg", "/king3.jpg"],
    category: "perfumes",
    rating: 4.8,
    reviews: 124,
    inStock: true,
    tags: ["bestseller", "luxury"],
    stock: 20,
  },
  {
    id: "14",
    sku: "LIO-PRF-002",
    name: "Afnan 9PM Rebel",
    description: "A vibrant fruity-sweet fragrance opening with mandarin and pineapple, revealing cedarwood warmth and a smooth caramel-musk finish.",
    price: 2800,
    image: "/91.jpg",
    images: ["/91.jpg", "/92.jpg", "/93.jpg"],
    category: "perfumes",
    rating: 4.7,
    reviews: 89,
    inStock: true,
    tags: ["new"],
    stock: 20,
  },
  {
    id: "15",
    sku: "LIO-PRF-003",
    name: "Bade'e Al Oud Oud for Glory",
    description: "An intense, darkly luxurious Oriental Woody fragrance featuring spicy Saffron and deep Oud, tailored for a sophisticated presence.",
    price: 4000,
    image: "/b1.jpg",
    images: ["/b1.jpg", "/b2.jpg", "/b3.jpg"],
    category: "perfumes",
    rating: 4.9,
    reviews: 215,
    inStock: true,
    tags: ["premium", "luxury"],
    stock: 20,
  },
  {
    id: "16",
    sku: "LIO-PRF-004",
    name: "Lattafa Khamrah",
    description: "A warm, spicy, and creamy gourmand masterpiece blending Cinnamon, Dates, and Praline for an addictive and elegant aura.",
    price: 5000,
    image: "/l1.jpg",
    images: ["/l1.jpg", "/l2.jpg", "/l3.jpg"],
    category: "perfumes",
    rating: 4.6,
    reviews: 56,
    inStock: true,
    tags: ["sale"],
    stock: 20,
  },
  {
    id: "17",
    sku: "LIO-PRF-005",
    name: "Dior Sauvage",
    description: "A powerful and noble composition. Fresh, raw and noble at the same time. The excessive overdose of it is an olfactory signature.",
    price: 4500,
    image: "/su1.jpg",
    images: ["/su1.jpg", "/su2.jpg", "/su3.jpg"],
    category: "perfumes",
    rating: 4.8,
    reviews: 420,
    inStock: true,
    tags: ["bestseller", "popular"],
    stock: 20,
  },
  {
    id: "18",
    sku: "LIO-PRF-006",
    name: "Valentino Donna Born In Roma Intense",
    description: "A magnetic floral ambery fragrance glorifying Vanilla and Jasmine, capturing the essence of Rome's passionate nightfall.",
    price: 5500,
    image: "/perfumes/v1.jpg",
    images: ["/perfumes/v1.jpg", "/perfumes/v2.jpg", "/perfumes/v3.jpg"],
    category: "perfumes",
    rating: 4.9,
    reviews: 42,
    inStock: true,
    tags: ["new", "luxury"],
    stock: 20,
  },
]

export const categories = [
  { id: "clothes", name: "Clothes", icon: "shirt", count: 4 },
  { id: "shoes", name: "Shoes", icon: "footprints", count: 4 },
  { id: "cosmetics", name: "Cosmetics", icon: "sparkles", count: 4 },
  { id: "perfumes", name: "Perfumes", icon: "spray-can", count: 4 },
] as const

export function getProductsByCategory(category: string): Product[] {
  return products.filter((p) => p.category === category)
}

export function getProductById(id: string): Product | undefined {
  return products.find((p) => p.id === id)
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.tags?.includes("bestseller"))
}

export function searchProducts(query: string): Product[] {
  const lowerQuery = query.toLowerCase()
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(lowerQuery) ||
      p.description.toLowerCase().includes(lowerQuery) ||
      p.category.toLowerCase().includes(lowerQuery),
  )
}
